spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book_rental
    driver-class-name: org.mariadb.jdbc.Driver
    username: springuser
    password: springuserpass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
  h2:
    console:
      enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: OFF